### ISSUE TITLE
st7111 receivers???

### ISSUE THREAD

**Issue by ahmedmoselhi** [OpenVisionE2/blindscan-s2#1]
can this source files be used in sh4 stb's like amiko alien 8900 in enigma2????

**Comment by kueken** [comment]
https://github.com/OpenVisionE2/blindscan-s2

**Comment by kueken** [comment]
https://github.com/OpenVisionE2/meta-fulan/commit/8533658e4408ab2207d6a4aef8e4c8771873520b#diff-5d2ac0951015b5db73f2278a219a9dd7

Since the commit everything is directly over the top
